<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareLive.Protocol\HardwareLive.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Profiles\profiles.json" LogicalName="HardwareLive.Core.Profiles.profiles.json" />
  </ItemGroup>

</Project>
